### ISSUE TITLE
Thane station name

### ISSUE THREAD

**Issue by urbanemissions** [openaq/openaq.org#177]
When pulling a CSV file for this station, station name comes with quotes, making it hard to read the file with other stations.

**Comment by jflasher** [comment]
Hi @urbanemissions it looks like Thane is a city/region name and not a station name in the system. If I understand the issue correctly, you're saying when you do something like `https://api.openaq.org/v1/measurements?city=Thane&format=csv`, you get `"` around the location name which is something like `"Pimpleshwar Mandir, Dombivali - MPCB"`. This behavior is to be expected since there are `,` in the location name so it needs to be quoted or else the CSV file will be invalid.

Let me know if this isn't what you meant.

**Comment by urbanemissions** [comment]
good morning.  Yes, that is what I meant. I am processing the csv files through fortran for aggregating the data from other networks.. the quotes in the location name (with the additional comma in it) showed up as an error.

**Comment by jflasher** [comment]
Hmm, I wonder if there is some way to tell the Fortran CSV reader to use `"` as an enclosing character? Not much we can do API side since we need to `"` to prevent the `,` character from breaking into a new field.

**Comment by jflasher** [comment]
Not something we can change via API, so closing here.
