### ISSUE TITLE
Locations dashboard [Epic]

### ISSUE THREAD

**Issue by jvntf** [openaq/openaq.org#426]
Set up generic layout to display cards in grid
![image](https://user-images.githubusercontent.com/19439427/98034600-42c73580-1de5-11eb-85b5-91b250d6450c.png)

**Comment by rwegener2** [comment]
This ticket encompasses several smaller tasks listed below in prioritized order with a link to their own ticket or card:
1. Time series data (by particulate) #423 
2. Latest Measurements, Source, and Details cards [card link](https://github.com/openaq/openaq.org/projects/1#card-49164978)
6. Temporal Coverage (by particulate) #424 

The following tickets were not numbered because they were not indicated as being very useful in the user survey and we are reevaluating how we would like to move forward:
-  #420
-  #422 

The [Epic] label in the title in intended to signal that this task encompasses several others.
