### ISSUE TITLE
add mobile map to the datasets page & update locations mobile map

### ISSUE THREAD

**Issue by rwegener2** [openaq/openaq.org#621]
## Goal
Display a map with the more details points of mobile locations in a dataset similar to how we do on the locations page.  These changes apply only to locations or datasets where the isMobile field is True.

## Details
The maps should both use a new endpoint to display mobile data:
> Changes just deployed to staging:
Created new endpoint /v2/locations/tiles/mobile-generalized/{z}/{x}/{y}.pbf
"default" layer has the generalized/grouped points which only has the locationId
"bounds" has the bounding box which has all the same attributes as the single static points
I removed the "bounds" layer from the /v2/locations/tiles/{z}/{x}/{y}.pbf
The actual measurement data filtered by time for mobile locations is still at /v2/locations/tiles/mobile/{z}/{x}/{y}.pbf, but I'm not sure if we still want to use that or if it would just be better to use the mobile-generalized endpoint
These are all pushed up to staging and the viewer to see working sample is up at https://b4qc1cqcm2.execute-api.us-east-1.amazonaws.com/v2/locations/tiles/viewer

This should display all of the points of the location instead of the one that previously just had a few weeks of info.
For the dataset this should display all of the locations in that dataset, up to 15 nodes.  Greater than 15 locations I think it should say something like "map view not available with greater than 15 nodes".  This shouldn't be a warning that gets used with the current data, since all of the mobile datasets have fewer than 15 locations right now.

**Comment by AliceR** [comment]
Breaking down into frontend tasks:
- [ ] use new endpoint /v2/locations/tiles/mobile-generalized/{z}/{x}/{y}.pbf (with or without locationId parameter?) for mobile-source currently being used with mobile data card on location dashboard
- [ ] change layer bounds to use the mobile-source and (instead of regular /v2/locations/tiles/{z}/{x}/{y}.pbf endpoint)
- [ ] add the mobile data card to project dashboards if isMobile is true for the project - with dateFrom and dateTo parameters from project?
- [ ] implement error message for projects with more than 15 locations
