### ISSUE TITLE
1 month date selection doesn't show hour of day Ex. https://openaq-staging.org/#/location/62216?dateRange=2021/1

### ISSUE THREAD

**Issue by jvntf** [openaq/openaq.org#641]

**Comment by jvntf** [comment]
@rwegener2 per this [issue](https://github.com/openaq/openaq.org/issues/558), only Mobile locations should show HOD for month time period. Has this changed?

**Comment by rwegener2** [comment]
sorry, @jvntf this was not written out well.  On the time series all types of data should show one point per hour for both the one day date selection and one month date selection.

It's possible that some of these stations aren't reporting every hour, but I would think the station listed being a PurpleAir sensor would have had more data points.  If it turns out that we are reporting the most highly resolved measurement this station is reporting then we can close the issue without a change.
